const policy = {
  schemaVersion: 1,
  policyVersion: "research-guided-route-candidates-v1",
  limits: {
    maximumPlanBytes: 256 * 1_024,
    maximumOptionsBytes: 1_024,
    maximumProposals: 6,
    maximumViaCandidatesPerProposal: 5,
    maximumMappedNetworkCandidatesPerProposal: 8,
    maximumExploredCombinations: 512,
    maximumEvidenceReferencesPerCandidate: 32,
    maximumEvidenceReferencesPerProposal: 64,
    maximumSelectionReasonsPerCandidate: 8,
    maximumVerificationCodes: 32,
    maximumRequirementItems: 48,
    maximumEvidenceGaps: 96,
    maximumKnownLimitations: 32,
    maximumStringLength: 160
  },
  supportedActivities: ["hiking", "trail_running"],
  supportedRouteTypes: ["loop", "point_to_point", "out_and_back"],
  strategies: [
    "must_have_first",
    "balanced_experiences",
    "minimal_preliminary_detour",
    "mapped_network_first",
    "overnight_candidate_first"
  ],
  candidateRoles: [
    "must_have",
    "preferred",
    "facility_candidate",
    "overnight_candidate"
  ],
  selectionReasons: [
    "required_experience",
    "preferred_experience",
    "required_facility",
    "overnight_request",
    "available_research_candidate",
    "lower_preliminary_distance",
    "mapped_network_context"
  ],
  verificationCodes: [
    "real_routing_required",
    "connectivity_required",
    "actual_distance_required",
    "actual_duration_required",
    "actual_elevation_required",
    "public_access_required",
    "access_restriction_required",
    "closure_status_required",
    "trail_difficulty_required",
    "trail_visibility_required",
    "exposure_required",
    "steep_climb_required",
    "opening_status_required",
    "seasonal_operation_required",
    "overnight_permission_required",
    "booking_required",
    "water_status_required",
    "current_conditions_required",
    "transport_required",
    "mobility_suitability_required",
    "child_suitability_required",
    "beginner_suitability_required",
    "endpoint_coordinate_required",
    "official_status_required",
    "legal_sleep_required"
  ],
  requirementTypes: [
    "must_have_experience",
    "preferred_experience",
    "required_facility",
    "avoidance",
    "group_safeguard",
    "overnight",
    "transport",
    "date_or_season",
    "route_constraint",
    "candidate_verification",
    "region_coverage"
  ],
  requirementValues: [
    "viewpoint",
    "waterfall",
    "peak",
    "lake",
    "forest",
    "quiet_trails",
    "official_hiking_route",
    "alpine_hut",
    "wilderness_hut",
    "landmark",
    "drinking_water",
    "lunch_hut",
    "emergency_shelter",
    "public_transport",
    "official_campsite",
    "designated_bivouac",
    "toilets",
    "exposed_trails",
    "technical_terrain",
    "major_roads",
    "steep_climbs",
    "repeated_path",
    "crowds",
    "unpaved_surface",
    "beginner_group",
    "children_group",
    "limited_mobility_group",
    "overnight_stay",
    "exact_date",
    "season",
    "maximum_technical_difficulty",
    "maximum_elevation_gain",
    "distance_target",
    "route_endpoint",
    "candidate_public_access",
    "candidate_closure_status",
    "full_region_coverage"
  ],
  evidenceGapCodes: [
    "missing_access_evidence",
    "missing_opening_evidence",
    "missing_overnight_evidence",
    "missing_water_evidence",
    "missing_current_conditions",
    "missing_official_status",
    "missing_route_connection",
    "missing_seasonal_evidence",
    "unsupported_region",
    "partial_region_coverage",
    "insufficient_candidate_count",
    "unsupported_activity",
    "unresolved_geography",
    "no_usable_candidates",
    "must_have_shortfall",
    "waypoint_budget_exceeded",
    "unsupported_experience",
    "facility_unverified",
    "overnight_unverified",
    "transport_unverified",
    "date_or_season_unverified",
    "terrain_constraint_unverified",
    "group_suitability_unverified",
    "distance_lower_bound_exceeds_target",
    "candidate_access_denied",
    "candidate_currently_closed",
    "access_restriction_unverified",
    "incompatible_difficulty",
    "official_status_unverified",
    "route_endpoint_unavailable",
    "dossier_freshness_not_current"
  ],
  limitationCodes: [
    "access_unverified",
    "access_restriction_unverified",
    "opening_unverified",
    "overnight_legality_unverified",
    "water_availability_unverified",
    "current_conditions_unavailable",
    "source_stale",
    "source_timestamp_unavailable",
    "conflicting_authoritative_evidence",
    "mapped_presence_only",
    "terrain_derived_only",
    "partial_regional_coverage",
    "official_status_unverified",
    "route_connection_unverified",
    "insufficient_evidence",
    "requires_real_routing",
    "endpoint_unavailable",
    "lower_bound_exceeds_target",
    "trail_difficulty_unverified",
    "exposure_unverified",
    "bookability_unverified",
    "seasonal_status_unverified",
    "transport_unverified",
    "mobility_suitability_unverified",
    "child_suitability_unverified",
    "beginner_suitability_unverified"
  ],
  preliminaryDistance: {
    kind: "straight_line_lower_bound",
    limitationCode: "requires_real_routing",
    heuristicMinimumMultiplier: 1.15,
    heuristicMaximumMultiplier: 1.65,
    roundingDecimals: 3
  },
  difficultyOrder: [
    "strolling",
    "hiking",
    "mountain_hiking",
    "demanding_mountain_hiking",
    "alpine_hiking",
    "demanding_alpine_hiking",
    "difficult_alpine_hiking"
  ],
  experienceCategoryMap: {
    viewpoint: "viewpoint",
    waterfall: "waterfall",
    peak: "peak",
    lake: "lake",
    alpine_hut: "alpine_hut",
    wilderness_hut: "wilderness_hut",
    landmark: "landmark"
  },
  minimumProposalEntityDifference: 1,
  maximumProposalEntitySetOverlap: 0.8
};

export const RESEARCH_GUIDED_ROUTE_CANDIDATE_POLICY_V1 = deepFreeze(policy);

function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) deepFreeze(child);
  return value;
}
