// Generated by backend/scripts/configure-research-app.js from reviewed public deployment metadata.
// An absent deployment remains unavailable; no placeholder host is trusted.
nonisolated enum ResearchDeploymentIdentity {
    static let stagingHost: String? = nil
    static let productionHost: String? = nil
}
